// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandApprovalRequest } from "./CommandApprovalRequest";
import type { CommandApprovalResolution } from "./CommandApprovalResolution";
import type { TraceEvent } from "./TraceEvent";

export type AgentEvent = { trace: TraceEvent, approvalRequest: CommandApprovalRequest | null, approvalResolution: CommandApprovalResolution | null, };
