// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuiMessage } from "./GuiMessage";
import type { GuiSessionListItem } from "./GuiSessionListItem";

export type ConversationPanel = { activeSessionId: string, messageCount: number, messages: Array<GuiMessage>, sessions: Array<GuiSessionListItem>, };
