// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingEvidence } from "./FindingEvidence";
import type { FindingSeverity } from "./FindingSeverity";
import type { FindingStatus } from "./FindingStatus";

export type FindingPreview = { id: string, status: FindingStatus, statusLabel: string, severity: FindingSeverity, severityLabel: string, confidenceLabel: string, title: string, location: string, taxonomy: string | null, summary: string, evidence: Array<FindingEvidence>, remediation: string, nextAction: string, };
