// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuiContextUsage = { windowTokens: number, usedTokens: number, freeTokens: number, systemTokens: number, toolTokens: number, messageTokens: number, usedPercent: number, freePercent: number, systemPercent: number, toolPercent: number, messagePercent: number, estimatorLabel: string, };
