// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuiSessionListItem = { id: string, title: string, status: string, updatedAt: string, messageCount: number, preview: string, canArchive: boolean, };
