// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunPhase } from "./RunPhase";

export type RunPanel = { phase: RunPhase, label: string, statusDetail: string, busy: boolean, canSend: boolean, canCancel: boolean, primaryActionLabel: string, pendingLabel: string, pendingDetail: string, };
