// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuiContextUsage } from "./GuiContextUsage";
import type { GuiTokenUsage } from "./GuiTokenUsage";

export type StatusPanel = { agentLabel: string, model: string, sessionStatus: string, sessionPath: string, context: GuiContextUsage, activeContext: GuiContextUsage, tokenUsage: GuiTokenUsage, messageCount: number, traceCount: number, toolCount: number, findingCount: number, };
