// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolParameterKey } from "./ToolParameterKey";

export type ToolParameter = { key: ToolParameterKey, name: string, label: string, description: string, typeName: string, required: boolean, };
