// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolParameterKey = "arguments" | "command" | "content" | "context_lines" | "cwe_id" | "glob_filter" | "limit" | "max_depth" | "max_results" | "offset" | "path" | "pattern" | "project_path" | "query" | "recursive" | "ruleset" | "skill_name" | "timeout_secs" | "other";
