// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TraceEventKind = "state" | "think" | "token" | "tool_call" | "tool_confirm" | "tool_result" | "context_compaction" | "error";
